export interface ContainerStats {
	cpu_stats:{
		cpu_usage:{
			total_usage:number,
			system_cpu_usage:number;
		},
		system_cpu_usage:number,
		online_cpus:number,
	},
	precpu_stats:{
		cpu_usage:{
			total_usage:number,
			system_cpu_usage:number;
		},
		system_cpu_usage:number,
		online_cpus:number,
	},
	memory_stats:{
		usage:number,
		stats:{
			cache:number,
		}
	},
	networks:unknown
}
